( COKLU YUZEY TARAMA )
( G-Code generated by ait-cnc-cli )
( 21.03.2022 12:24:19 )
O 1001
G17 G21 G90 G54
G40 G49 G80
( pass_count: 2 )
( surface_speed: 1256.6370614359173 )
( tool_diameter: 50 )
( Z_CLEARANCE: 20 )
T3 M6
G43 H3 Z20
S4000 M03
M8
( Pass: 1 )
G0 X-35 Y-25 
G0 Z6.2
G1 X211.5 F1000
G0 Z20
( Pass: 2 )
G0 X-35 Y-70 
G0 Z6.2
G1 X211.5 F1000
G0 Z20
M05
M9
M30
